In [2]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[3,4,5]])
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
print(arr[0])
display(arr[1])


[1 2 3]


array([3, 4, 5])

In [9]:
ary = np.arange(2,10,2)
ary


array([2, 4, 6, 8])

In [17]:
# menambah isi array
ap=np.append(ary,[1,2])
ap

array([2, 4, 6, 8, 1, 2])

In [20]:
# delete isi array
delit=np.delete(ap,2)
delit


array([2, 4, 8, 1, 2])

In [22]:
# sort
np.sort(delit,)


array([1, 2, 2, 4, 8])

In [24]:
# array3d
arr3d = np.array([
    [[1,2,3],
    [4,5,6]],
    [[7,8,9],
     [11,22,33]],
     [[13,23,45],
     [45,22,44]]
])

print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 22 33]]

 [[13 23 45]
  [45 22 44]]]


In [27]:
# menunjukan dimensi array
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.size)

3
(3, 2, 3)
18


In [46]:
# reshape array
resh= np.arange(10)
print(resh)
done_resh = resh.reshape(2,5)
print("\n")
print(done_resh)
print(done_resh.ndim)

[0 1 2 3 4 5 6 7 8 9]


[[0 1 2 3 4]
 [5 6 7 8 9]]
2


In [50]:
# up dimension
a2=resh[np.newaxis]
print(a2)


[[0 1 2 3 4 5 6 7 8 9]]


In [51]:
data = np.array([1,2,3]) 
print(data) 
print(data[0])
print(data[1]) 
print(data[0:2]) 
print(data[1:]) 
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [53]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) 
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
print(a[a>=5])
print(a[(a % 2) & (a>6)])

[ 5  6  7  8  9 10 11 12]
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]

 [[5 6 7 8]
  [1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]]


In [60]:
arr = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr1 = arr[3:8] 
arr1

array([4, 5, 6, 7, 8])

In [79]:
arr_a= np.array([[1,2,3],
                 [4,6,5]])

arr_b= np.array([[2,2,5],
                 [4,6,5]])
print(arr_a)
print(arr_b)
print("\n")
avstack = np.vstack((arr_a,arr_b))
print(avstack)
print("\n")
ahstack = np.hstack((arr_a,arr_b))
print(ahstack)


[[1 2 3]
 [4 6 5]]
[[2 2 5]
 [4 6 5]]


[[1 2 3]
 [4 6 5]
 [2 2 5]
 [4 6 5]]


[[1 2 3 2 2 5]
 [4 6 5 4 6 5]]


In [81]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [84]:
split=np.hsplit(arrsplit,3)
split

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [87]:
arrsplit.view()

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [90]:
copy = arrsplit.copy()
copy

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [92]:
a = np.array([1, 2, 3, 4]) # Add all of the elements in the array 
a.sum()

10

In [95]:
b = np.array([[1, 1], [2, 2]])   
b.sum(axis=0) # jika axis = 0 maka menjumlahkan rows dan jika axis =1 maka menjumlahkan column

array([3, 3])

In [99]:
data=np.array([[1,2],[3,4]])
print(data)
angka =2
jml = data*angka
jml

[[1 2]
 [3 4]]


array([[2, 4],
       [6, 8]])

In [101]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652], 
              [0.54627315, 0.05093587, 0.40067661, 0.55645993], 
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)


[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [106]:
print(A.max())
print(A.min())
print(A.sum())  
print(A.max(axis=0)) #rows
print(A.max(axis=1))#columns

0.82485143
0.05093587
4.8595784
[0.54627315 0.82485143 0.40067661 0.56917101]
[0.5510652  0.55645993 0.82485143]


In [113]:
z = np.zeros((6,2))
o = np.ones((6,2))
z+o

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [120]:
a1 = np.array([[0,1,2],[2,3,4]])
print(a1.shape)
a2 = np.array([[0,1,2],[3,4,5],[8,4,6]])
print(a2.shape)
print(a1)
print(a2)

(2, 3)
(3, 3)
[[0 1 2]
 [2 3 4]]
[[0 1 2]
 [3 4 5]
 [8 4 6]]


In [122]:
np.dot(a1,a2)

array([[19, 12, 17],
       [41, 30, 43]])

In [124]:
# indexing di matrix

print(a2)
print(a2[0])
print(a2[1])
print(a2[0,2])
print(a2[1:3])


[[0 1 2]
 [3 4 5]
 [8 4 6]]
[0 1 2]
[3 4 5]
2
[[3 4 5]
 [8 4 6]]


In [128]:
print(a2)
print("\n")
print(a2.T)

[[0 1 2]
 [3 4 5]
 [8 4 6]]


[[0 3 8]
 [1 4 4]
 [2 5 6]]


In [137]:
a=np.arange(6)
a2=a[np.newaxis]
a2.T
# print(a.T)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [142]:
a3=a2.reshape(2,3)
a3

array([[0, 1, 2],
       [3, 4, 5]])

In [145]:
a4 = a3.flatten()
a5=a3.ravel()
print(a5)
print(a4)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
